#!/bin/sh
java -cp lib/jortho.jar:lib/stax-utils.jar:lib/apache-mime4j-0.6.jar:lib/commons-codec-1.3.jar:lib/commons-logging-1.1.1.jar:lib/httpclient-4.1-alpha1.jar:lib/httpcore-4.1-alpha1.jar:lib/httpmime-4.1-alpha1.jar:.:build main.BMovieApp $1 $2 $3 $4 
